version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
  test:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - run:
        name: "Pull Submodules"
        command: |
          git submodule init
          git submodule update --remote
      - run: graphp/tests/run_tests.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
