version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
  test:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - run: graphp/tests/run_tests.sh
